package com.school.app.commons;

public interface DBQueries {
	String INSERT_USERS = "INSERT INTO USERS ( ID, NAME, AGE, CITY, STATE, UUID_CODE ) VALUES ( HIBERNATE_SEQUENCE.NEXTVAL, :name, :age, :city, :state, :uuid )";
	String SELECT_ALL_USERS = "SELECT ID, NAME, AGE, CITY, STATE,UUID_CODE FROM USERS";
	String SELECT_USERS_BY_ID = "SELECT ID, NAME, AGE, CITY, STATE,UUID_CODE FROM USERS WHERE UUID_CODE=:id";
	String DELETE_USERS_BY_ID = "DELETE FROM USERS WHERE UUID_CODE=:id";
	String UPDTE_USERS_BY_ID="UPDATE USERS SET NAME = :name, AGE = :age, CITY = :city, STATE = :state WHERE id = :id";
	String SELECT_ALL_STATES = "SELECT ID, CODE, STATE_NAME,CAPITAL FROM STS_CTY";
}
